package com.industriousgnomes.dnd.character.feature;

public enum FeatureType {
    HIT_POINTS, HIT_DIE, INITIAL_HIT_DIE,

    MOVEMENT_SPEED, DARKVISION,

    ATTACK_MODIFIER, ARMOR_CLASS, NATURAL_ARMOR_CLASS, DAMAGE_MODIFIER, RANGED, MELEE,

    ABILITY, STRENGTH, STRENGTH_BASE, STRENGTH_ABILITY_MODIFIER, STRENGTH_SAVING_THROW, DEXTERITY, DEXTERITY_BASE, DEXTERITY_ABILITY_MODIFIER, DEXTERITY_SAVING_THROW, INTELLIGENCE, INTELLIGENCE_BASE, INTELLIGENCE_ABILITY_MODIFIER, INTELLIGENCE_SAVING_THROW, WISDOM, WISDOM_BASE, WISDOM_ABILITY_MODIFIER, WISDOM_SAVING_THROW, CONSTITUTION, CONSTITUTION_BASE, CONSTITUTION_ABILITY_MODIFIER, CONSTITUTION_SAVING_THROW, CHARISMA, CHARISMA_BASE, CHARISMA_ABILITY_MODIFIER, CHARISMA_SAVING_THROW,

    SKILL, ACROBATICS, 		// DEX
    ANIMAL_HANDLING, 	// WIS
    ARCANA, 			// INT
    ATHLETICS, 			// STR
    DECPTION, 			// CHA
    HISTORY, 			// INT
    INSIGHT, 			// WIS
    INTIMIDATION, 		// CHA
    INVESTIGATION, 		// INT
    MEDICINE, 			// WIS
    NATURE, 			// INT
    PERCEPTION, 		// WIS
    PERFORMANCE, 		// CHA
    PERSUASION, 		// CHA
    RELIGION, 			// INT
    SLIGHT_OF_HAND, 	// DEX
    STEALTH, 			// DEX
    SURVIVAL, 			// WIS

    PROFICIENCY,

    ARMOR, LIGHT_ARMOR, PADDED, LEATHER, STUDDED_LEATHER, MEDIUM_ARMOR, HIDE, CHAIN_SHIRT, SCALE_MAIL, BREASTPLATE, HALF_PLATE, HEAVY_ARMOR, RING_MAIL, CHAIN_MAIL, SPLINT, PLATE, SHIELD,

    WEAPON, SIMPLE_WEAPONS, SIMPLE_MELEE_WEAPONS, CLUB, DAGGER, GREATCLUB, HANDAXE, JAVELIN, LIGHT_HAMMER, MACE, QUARTERSTAFF, SICKLE, SPEAR, SIMPLE_RANGED_WEAPONS, LIGHT_CROSSBOW, DART, SHORTBOW, SLING, MARTIAL_WEAPONS, MARTIAL_MELEE_WEAPONS, BATTLEAXE, FLAIL, GLAIVE, GREATSWORD, HALBERD, LANCE, LONGSWORD, MAUL, MORNINGSTAR, PIKE, RAPIER, SCIMITAR, SHORTSWORD, TRIDENT, WAR_PICK, WARHAMMER, WHIP, MARTIAL_RANGED_WEAPONS, BLOWGUN, HAND_CROSSBOW, HEAVY_CROSSBOW, LONGBOW, NET, zzz
}
